#!/bin/sh
for i
do
	d=`dirname $i`
	f=`basename $i .ir`
	echo -n "$d/$f: "
	java -jar IRInterp.jar $d/$f.ir 1> $d/$f.out
	if [ -r $d/$f.out.ref ]; then
          diff -w $d/$f.out $d/$f.out.ref > $d/$f.out.diff; 
          if [ -s $d/$f.out.diff ]; then 
            echo "differs from ref (see $f.out.diff)"; 
          else
            echo "matches ref"; 
	    rm $d/$f.out.diff; 
          fi
	else
            echo "no ref to compare"; 
        fi
done
exit 0

